import { HistoryClient } from "@/components/gallery/history-client"
import { auth } from "@clerk/nextjs/server"
import { redirect } from "next/navigation"

export const metadata = {
    title: "Your History | Bloom Studio",
    description: "View all your generated images in one place.",
}

/**
 * History page - displays all images generated by the current user.
 */
export default async function HistoryPage() {
    const { userId } = await auth()

    if (!userId) {
        redirect("/sign-in")
    }

    return (
        <div className="min-h-screen">
            <div className="container mx-auto px-4 py-8">
                <div className="mb-8">
                    <h1 className="text-3xl font-bold mb-2">Your History</h1>
                    <p className="text-muted-foreground">
                        All the images you've created, from newest to oldest.
                    </p>
                </div>
                <HistoryClient />
            </div>
        </div>
    )
}
