import { HistoryClient } from "@/components/gallery/history-client"
import { getMyImagesWithDisplayDataCached } from "@/app/_server/cache/history"
import { auth } from "@clerk/nextjs/server"
import type { Metadata } from "next"
import { redirect } from "next/navigation"

export const metadata: Metadata = {
    title: "Your History | Bloom Studio",
    description: "View all your generated images in one place.",
    robots: {
        index: false,
        follow: false,
    },
}

/**
 * History page - displays all images generated by the current user.
 * Fetches initial page from server-side cache for faster load and reduced Convex bandwidth.
 */
export default async function HistoryPage() {
    const { userId } = await auth()

    if (!userId) {
        redirect("/sign-in")
    }

    // Fetch initial page on server (cached per-user)
    const initialPage = await getMyImagesWithDisplayDataCached(userId, null)

    return (
        <div className="min-h-screen">
            <div className="container mx-auto px-4 py-8">
                <div className="mb-8">
                    <h1 className="text-3xl font-bold mb-2">Your History</h1>
                    <p className="text-muted-foreground">
                        All the images {"you've"} created, from newest to oldest.
                    </p>
                </div>
                <HistoryClient initialPage={initialPage} />
            </div>
        </div>
    )
}
